-- Demonstration data only. Run after the schema migration.
-- Existing records are not overwritten.
insert into public.restaurants (id,name,slug,tagline,description,address,hours,accent,currency,categories,published) values ('11111111-1111-4111-8111-111111111111','BRASA','brasa','Cocina de autor · Buenos Aires','Ingredientes de estación. Fuego lento. Platos para compartir.','Palermo, Buenos Aires · Restaurante de ejemplo','Mar a dom · 12:00 a 23:00','#c84924','ARS',ARRAY['Para empezar','Principales','Postres','Bebidas'],true) on conflict (id) do nothing;
insert into public.restaurants (id,name,slug,tagline,description,address,hours,accent,currency,categories,published) values ('22222222-2222-4222-8222-222222222222','VERDE','verde','Cocina natural · Buenos Aires','Una pausa fresca, hecha con ingredientes de estación.','Belgrano, Buenos Aires · Restaurante de ejemplo','Lun a sáb · 09:00 a 20:00','#35694c','ARS',ARRAY['Para empezar','Principales','Bebidas'],true) on conflict (id) do nothing;
insert into public.dishes (id,restaurant_id,name,description,price,category,image_url,model_url,usdz_url,available,featured,demo_model,allergens,sort_order) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','11111111-1111-4111-8111-111111111111','Palta de estación','Palta fresca, aceite de oliva y sal en escamas. Un comienzo simple para compartir.',7800,'Para empezar','/media/avocado.jpg','/models/avocado.glb','',true,true,true,'',0) on conflict (id) do nothing;
insert into public.dishes (id,restaurant_id,name,description,price,category,image_url,model_url,usdz_url,available,featured,demo_model,allergens,sort_order) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','11111111-1111-4111-8111-111111111111','Burger de la casa','Medallón a la parrilla, cheddar, vegetales frescos y nuestro aderezo, en pan tostado.',14500,'Principales','/media/burger.jpg','','',true,true,false,'Gluten, leche, huevo',1) on conflict (id) do nothing;
insert into public.dishes (id,restaurant_id,name,description,price,category,image_url,model_url,usdz_url,available,featured,demo_model,allergens,sort_order) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3','11111111-1111-4111-8111-111111111111','Pizza margarita','Masa de fermentación lenta, salsa de tomates, mozzarella y albahaca fresca.',16900,'Principales','/media/pizza.jpg','','',true,false,false,'Gluten, leche',2) on conflict (id) do nothing;
insert into public.dishes (id,restaurant_id,name,description,price,category,image_url,model_url,usdz_url,available,featured,demo_model,allergens,sort_order) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4','11111111-1111-4111-8111-111111111111','Postre de chocolate','Chocolate intenso, textura suave y un final para disfrutar sin apuro.',8200,'Postres','/media/dessert.jpg','','',true,false,false,'Leche, huevo, gluten',3) on conflict (id) do nothing;
insert into public.dishes (id,restaurant_id,name,description,price,category,image_url,model_url,usdz_url,available,featured,demo_model,allergens,sort_order) values ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1','22222222-2222-4222-8222-222222222222','Palta fresca','Palta madura, aceite de oliva y un toque de limón.',6900,'Para empezar','/media/avocado.jpg','/models/avocado.glb','',true,true,true,'',0) on conflict (id) do nothing;
