import { PGlite } from '@electric-sql/pglite';
import { readFile, readdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
// Supabase supplies these roles/schemas. Reproduce their RLS-relevant contract locally.
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key, email text, email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant usage on schema auth, public to anon,authenticated,service_role;
grant execute on function auth.uid() to anon,authenticated,service_role;
create schema storage;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;
grant usage on schema storage to anon,authenticated,service_role;
grant select,insert,update,delete on storage.objects to anon,authenticated;
grant execute on function storage.foldername(text) to anon,authenticated;`);
const migrations = (await readdir('supabase/migrations')).filter(v=>v.endsWith('.sql')).sort();
for (const file of migrations) await db.exec(await readFile(`supabase/migrations/${file}`,'utf8'));
const [admin,alice,bob] = ['a','b','c'].map(c=>`${c.repeat(8)}-${c.repeat(4)}-4${c.repeat(3)}-8${c.repeat(3)}-${c.repeat(12)}`);
const [r1,r2]=['1','2'].map(c=>`${c.repeat(8)}-${c.repeat(4)}-4${c.repeat(3)}-8${c.repeat(3)}-${c.repeat(12)}`);
await db.query('insert into auth.users(id) values ($1),($2),($3)',[admin,alice,bob]);
await db.query('insert into public.platform_admins values($1)',[admin]);
await db.query("insert into public.restaurants(id,name,slug,published) values ($1,'Brasa','brasa',true),($2,'Verde','verde',false)",[r1,r2]);
await db.query('insert into public.restaurant_members values($1,$2),($3,$4)',[r1,alice,r2,bob]);
await db.query("insert into public.dishes(restaurant_id,name,category,available) values($1,'Visible','Principales',true),($1,'Oculto','Principales',false),($2,'Privado','Principales',true)",[r1,r2]);
async function as(role,user=''){await db.exec(`reset role;set role ${role}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);}
let passed=0;
function check(ok,label){assert.ok(ok,label);passed++;console.log(`PASS ${label}`);}
async function denied(sql,params,label){let rejected=false;try{await db.query(sql,params);}catch{rejected=true;}check(rejected,label);}
await as('anon');
check((await db.query('select * from restaurants')).rows.length===1,'public can read only published restaurants');
check((await db.query('select * from dishes')).rows.length===1,'public cannot read hidden or draft dishes');
await denied("insert into dishes(restaurant_id,name,category) values($1,'Hack','Principales')",[r1],'anonymous writes rejected');
await as('authenticated',alice);
check((await db.query('select * from restaurants')).rows.length===1,'restaurant A cannot read draft restaurant B');
check((await db.query('select * from dishes')).rows.length===2,'restaurant A sees its hidden dishes');
check((await db.query('select * from restaurant_members')).rows.length===1,'memberships are private');
check((await db.query('update dishes set price=123 where restaurant_id=$1 returning id',[r1])).rows.length===2,'owner can update own dishes');
check((await db.query('update dishes set price=99 where restaurant_id=$1 returning id',[r2])).rows.length===0,'cross-restaurant update blocked');
check((await db.query('delete from dishes where restaurant_id=$1 returning id',[r2])).rows.length===0,'cross-restaurant delete blocked');
await denied("insert into dishes(restaurant_id,name,category) values($1,'Hack','Principales')",[r2],'cross-restaurant insert blocked');
await denied('update dishes set restaurant_id=$1 where restaurant_id=$2',[r2,r1],'dish cannot move between restaurants');
await denied('insert into platform_admins values($1)',[alice],'user cannot promote self to platform admin');
await denied('insert into restaurant_members values($1,$2)',[r2,alice],'user cannot join another restaurant');
await denied("update restaurants set slug='changed' where id=$1",[r1],'permanent QR URL protected');
await denied("insert into restaurants(name,slug) values('Hack','hack')",[],'restaurant account cannot create tenant');
await db.query("insert into storage.objects(bucket_id,name) values('dish-media',$1)",[`${r1}/photo.jpg`]);
check(true,'owner can upload into own restaurant folder');
await denied("insert into storage.objects(bucket_id,name) values('dish-media',$1)",[`${r2}/photo.jpg`],'cross-restaurant storage upload blocked');
await denied("update storage.objects set name=$1 where name=$2",[`${r2}/photo.jpg`,`${r1}/photo.jpg`],'storage reassignment blocked');
await denied("select manage_menu_sections($1,array['Changed'],array['Para empezar','Principales','Postres','Bebidas'])",[r2],'cross-restaurant section changes blocked');
await db.query("select manage_menu_sections($1,array['Parrilla','Postres'],array['Para empezar','Principales','Postres','Bebidas'],'Principales','Parrilla')",[r1]);
check((await db.query("select * from dishes where category='Parrilla'")).rows.length===2,'section rename preserves and moves every dish');
await denied("select manage_menu_sections($1,array['Postres'],array['Parrilla','Postres'])",[r1],'nonempty section cannot be deleted');
await denied("select manage_menu_sections($1,array['One'],array['outdated'])",[r1],'stale section edits rejected');
await denied("select manage_menu_sections($1,array['Parrilla','parrilla'],array['Parrilla','Postres'])",[r1],'duplicate section names rejected');
await denied("update restaurants set categories=array['Postres'] where id=$1",[r1],'direct category deletion cannot orphan dishes');
await denied("insert into dishes(restaurant_id,name,category) values($1,'Invalid','Missing')",[r1],'unknown section insert rejected');
const ids=(await db.query('select id from dishes where restaurant_id=$1 order by name',[r1])).rows.map(d=>d.id);
await db.query('select reorder_menu_dishes($1,$2)',[r1,ids]);
check((await db.query('select id from dishes where restaurant_id=$1 order by sort_order',[r1])).rows.map(d=>d.id).join()===ids.join(),'dish order saved atomically');
await denied('select reorder_menu_dishes($1,$2)',[r2,ids],'cross-restaurant reordering rejected');
await denied('select reorder_menu_dishes($1,$2)',[r1,[ids[0],ids[0]]],'duplicate ordering IDs rejected');
await as('authenticated',admin);
check((await db.query('select * from restaurants')).rows.length===2,'platform admin sees all restaurants');
check((await db.query('select * from dishes')).rows.length===3,'platform admin sees all dishes');
await db.query("insert into restaurants(name,slug) values('Nuevo','nuevo')");
check(true,'platform admin can create restaurants');
await db.query("insert into restaurant_clients(restaurant_id,contact_name,email,phone) values($1,'Contacto privado','cliente@example.com','1234')",[r1]);
check((await db.query('select * from restaurant_clients')).rows.length===1,'platform admin can manage client contacts');
await as('anon');
await denied('select * from restaurant_clients',[],'anonymous cannot read contact details');
await denied("select lookup_onboarding_user('cliente@example.com')",[],'anonymous cannot enumerate accounts');
await as('authenticated',alice);
check((await db.query('select * from restaurant_clients')).rows.length===0,'restaurant member cannot read private client contacts');
check((await db.query("update restaurant_clients set email='intruso@example.com' where restaurant_id=$1 returning restaurant_id",[r1])).rows.length===0,'restaurant member cannot overwrite contacts');
await denied("insert into restaurant_clients(restaurant_id,email) values($1,'intruso@example.com')",[r2],'restaurant member cannot create contacts');
await denied("select lookup_onboarding_user('cliente@example.com')",[],'restaurant account cannot enumerate auth emails');
await as('authenticated',admin);
await db.query('delete from restaurant_members where restaurant_id=$1 and user_id=$2',[r1,alice]);
await as('authenticated',alice);
check((await db.query('update dishes set price=999 where restaurant_id=$1 returning id',[r1])).rows.length===0,'revoked membership blocks subsequent writes even with the same session');
await db.exec('reset role');
await db.query("update auth.users set email='cliente@example.com',email_confirmed_at=now() where id=$1",[alice]);
await as('service_role');
check((await db.query("select * from lookup_onboarding_user('CLIENTE@example.com')")).rows[0].id===alice,'server resolves exact case-insensitive account email');
check((await db.query("select * from lookup_onboarding_user('%example.com')")).rows.length===0,'account resolver never uses wildcard matching');
await db.close();console.log(`\n${passed} security checks passed. Storage API and hosted Auth still require a real Supabase integration test.`);
